### ISSUE TITLE
⚜ Advanced Calculator⚜

### ISSUE THREAD

**Issue by lqdm12** [lqdm12/iKodenprojects#9]
I am doing projects how this for learn more 😄

**Comment by benmanuel12** [comment]
Hi, I just want to let you know that using the good first issue label suggests that the issue in question contains a problem suited for people learning how to contribute to repositories on GitHub and that web scrapers exist to collect and list issues with this label.
I am willing to give some feedback on your code but that is not really what issues are for as far as I know.

**Comment by lqdm12** [comment]
Sorry, I will delete or private the project, I am learning do this, and so
sorry, I am beginning.
